repository:
  name: 'aws-lambda-s3-cache-control-headers'
  description: 'Configure AWS Lambda to Automatically Set Cache-Control Headers on S3 Objects.'
  homepage: 'https://www.aaronfagan.ca/blog/2017/how-to-configure-aws-lambda-to-automatically-set-cache-control-headers-on-s3-objects/'
  default_branch: 'main'
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: 'bug'
    color: 'CC0000'
  - name: 'feature'
    color: '336699'
  # - name: 'first-timers-only'
  #   oldname: 'Help Wanted' # Include if renaming
